Mofiqul/dracula.nvim

README.md
I've been trying to make this work for a couple of hours looking through
other folks configs who also use it, and it would never have occured to
me that this would be the fix for the it showing no colors
I've attached two images (the the PR) of how it looks with and without option set. 
`vim.o.termguicolors = false`
`vim.o.termguicolors = true`
I added the mention in the code snippet, but if you'd rather have it in a note or something, LMK
Thank you for your work
/frede
=> Added mention of termguicolors in README

lua/lualine/themes/dracula-nvim.lua
I thought it would be nice to use the same colors as in the main theme, so this includes them
It also allows the user to specify `g:dracula_lualine_bg_color`, and default to the black value that is currently used. I've done this because I personally use the dracula tmux theme, and it looks very strange with the black lualine against the tmux bar.
The rest is just cleanup
=> Streamline lualine theme

lua/dracula/init.lua
Removes the ugly default ColorColumn dark red highlight (on the right below)
=> Added ColorColumn highlight

lua/dracula/init.lua
Changed [some](https://www.reddit.com/r/neovim/comments/rg97j4/treesitter_for_markdown/hoje1mg/?utm_source=reddit&utm_medium=web2x&context=3) highlight groups to support the tree-sitter markdown parser.
=> Highlight groups changed for Tree-sitter markdown parser.

lua/dracula/init.lua
The black color mapping was accidentally removed.
=> Add missing black color

README.md
This PR fixes README information regarding transparent_bg in vim setup
Also reported here:
https://github.com/Mofiqul/dracula.nvim/issues/31
=> Update transparent_bg information in README

lua/dracula/groups.lua
TS* highlight groups were [removed from nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/pull/3656). I don't have nvim-cmp setup so I didn't change those
=> update to use treesitter queries instead of removed TS highlight groups

lua/dracula/groups.lua
=> fix: typo in parameter group

README.md
* Changed Neovim requirement version to 0.8 in order to avoid W18: Invalid character in group name errors.
=> #53 (docs): update Readme, neovim version.

lua/dracula/groups.lua
There is an issue where the Selected buffer background is white, this PR aims to solve it.
Before:
After:
=> Add BufferLineBufferSelected for Bufferline Plugin

lua/dracula/groups.lua
This fixes the new groups after semantic token highlighting was merged in this PR: https://github.com/neovim/neovim/pull/21100
=> Added lsp semantic token highlighting

lua/dracula/groups.lua
Makes qualifiers like c++ `virtual` pink like they used to be
=> Added `@type.qualifier` highlight

lua/dracula/groups.lua
Ruby symbols aren't highlighted otherwise (when using TS)
Before:
After:
=> Add highlighting for @symbol

lua/dracula/groups.lua
Changes highlighting for `@property`. This adds a bit more of highlighting to CSS files when using Treesitter (which fixes #66)
Using Treesitter on CSS file, before:
Using Treesitter on CSS file, after:
Still isn't awesome: the selectors are using the same highlighting as the CSS properties... But this is coming from Treesitter itself (which is assigning `@property` to both the selector and css properties). I tried to check a few themes on the wild and every theme I checked has the same "problem" when using Treesitter.
=> Change `@property` highlighting (fix #66)

lua/dracula/groups.lua
Currently I think markdown without TreeSitter looks better than with it due to the extra styling. This changes the relevant highlighting groups to make markdown with TreeSitter look more like it does without, allowing you to benefit from the other features of TreeSitter e.g. correctly highlighted code blocks. This also adds the missing @text.reference highlight group that the markdown parser uses.
Specifically:
* make titles bold
* make special punctuation (*, -, #, numbers etc) cyan. Hashtags are in the same group as the others so, to my knowledge, can't be styled a different colour unlike the No TreeSitter styling
* add references (orange and bold). The colour can be changed but I think orange contrasts the yellow links well.
Current highlighting without TreeSitter
Current highlighting …
=> Change some TreeSitter highlights with markdown in mind

lua/dracula/groups.lua
This adds highlighting for the `LspCodelens` highlight group. I propose to colour it the same way that Diagnostic Hints are coloured, similarly to how it has been done [here](https://github.com/marko-cerovac/material.nvim/pull/144).
=> [feat] add LspCodelens highlighting

lua/dracula/groups.lua
This PR improves barbar highlight so that it makes the current tab more obvious. This matches the bufferline.nvim theme shipped in lunarvim. I have been using it for a while and it should be stable.
Before:
After:
=> Improve barbar highlight

README.md, colors/dracula-soft.lua, lua/dracula/init.lua, lua/dracula/palette-soft.lua
Introduces the 'soft' variant of the Dracula theme from VS Code.
The VS Code 'Dracula Soft' variant is not hardcoded values, it's calculated
by reducing the main colors' saturation by 20% in [transformSoft](https://github.com/dracula/visual-studio-code/blob/master/scripts/generate.js
).
I compared the ANSI colours in :term to the ANSI colours in VS Code terminal
to make sure they match there.
Left is wezterm with `:colorscheme dracula-soft` and right is vs code with theme Dracula Soft:
=> feat(theme): introduce 'dracula-soft' palette

lua/dracula/init.lua
Fixed previous PR issues. Now the configurations from both palettes are extended with the local configurations when loading the themes instead of when setting them up.
=> fix: Soft palette loading

lua/dracula/groups.lua
There is a gap between the separator and the selected buffer, and this PR aims to solve it.
There is a similar issue here.
https://www.reddit.com/r/neovim/comments/14mzaps/bufferline_plugin_help/
Before:
After:
=> Add BufferLineSeparator for Bufferline Plugin

lua/dracula/groups.lua
Missing gitsign highlights on telescope.
<h3>Before</h3>
<h3>After</h3>
=> feat(telescope gitsigns): add telescope missing gitsigns highlights

lua/dracula/groups.lua
This was cyan background before, which made it very hard to read. See screenshots
=> Change debugPc to a background color

lua/dracula/groups.lua
Lazyvim changed in Version 10 from alpha to [nvimdev/dashboard-nvim](https://github.com/nvimdev/dashboard-nvim).
The colors were selected analogous to PR #88
=> feat: support for nvimdev/dashboard-nvim

lua/dracula/init.lua
`vim.version()` was introduced in neovim v0.9, and `vim.notify_once()` was introduced on v0.7, so for users on outdated versions (<v0.7), the version check errors out instead of sending a notification 
i believe the most common outdated version is the v0.6 version that ubuntu/debian/etc. has. using `vim.fn.has()` and `vim.notify()` (available since v0.5) should be enough?
=> fix: use older methods to check for an incompatible version

README.md, lua/dracula/groups.lua
As discussed in #122 - applies the changes to support upstream nvim-treesitter >0.9.2
Breaking change as this raises minimum requirements to [neovim 0.9.2](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1892038942) and nvim-treesitter to (also) 0.9.2
I've simply ran `sed 's/@old_name/@new_name' -i lua/dracula/groups.lua`. Verified by opening a few different files (rust, yaml, and markdown) with the latest nvim-treesitter, and it seems to work without any issues (though this is very limited testing)
=> feat!: Added support for nvim-treesitter >0.9.2

lua/dracula/groups.lua
I guess [supporting TS >0.9.2](https://github.com/Mofiqul/dracula.nvim/pull/123) broke symbol highlighting, which was added on #69.
This PR should have it added back.
Before (ruby):
After (ruby):
=> Add back symbol highlighting

README.md, lua/dracula/groups.lua
Added support for a new, seemingly quite popular plugin, mini.icons.
I've tried to keep the originally defined colors as close as possible, but of course with the Dracula hues :-)
mini.icons defines these highlight groups:\
https://github.com/echasnovski/mini.icons/blob/6fc6877d58635a13efca456cb025f1dfbf59786d/doc/mini-icons.txt#L130
I also added a link to mini.indentscope, which was already supported :-)
=> feat: add support for mini.icons

README.md, lua/dracula/groups.lua
Add support for [mini.statusline](https://github.com/echasnovski/mini.statusline)
> [!Note]
> I used the current Lualine colorscheme for this, if the bar's colorscheme is supposed to be different then tell me and I'll gladly change it
Adds support for the following highlight groups:
- MiniStatuslineModeNormal
- MiniStatuslineModeInsert
- MiniStatuslineModeVisual
- MiniStatuslineModeReplace
- MiniStatuslineModeCommand
- MiniStatuslineInactive
- MiniStatuslineDevinfo
- MiniStatuslineFilename
- MiniStatuslineFileinfo
=> Add mini.statusline support

README.md, lua/dracula/groups.lua
Add support for [blink.cmp](https://github.com/Saghen/blink.cmp/)
Adds support for the following highlight groups:
- BlinkCmpLabel 
- BlinkCmpLabelDeprecated 
- BlinkCmpLabelMatch 
- BlinkCmpKind 
- BlinkCmpKindFunction 
- BlinkCmpKindConstructor 
- BlinkCmpKindVariable 
- BlinkCmpKindClass 
- BlinkCmpKindInterface 
- BlinkCmpKindModule 
- BlinkCmpKindProperty 
- BlinkCmpKindOperator 
- BlinkCmpKindReference 
- BlinkCmpKindUnit 
- BlinkCmpKindValue 
- BlinkCmpKindField 
- BlinkCmpKindEnum 
- BlinkCmpKindKeyword 
- BlinkCmpKindSnippet 
- BlinkCmpKindColor 
- BlinkCmpKindFile 
- BlinkCmpKindFolder 
- BlinkCmpKindEvent 
- BlinkCmpKindEnumMember 
- BlinkCmpKindConstant 
- BlinkCmpKindStruct 
- BlinkCmpKindTypeParameter
=> Add blink.cmp support

lua/dracula/groups.lua
This PR adds definitions for the [mini.files](https://github.com/echasnovski/mini.files/blob/main/lua/mini/files.lua#L88) highlight groups:
```
--- * `MiniFilesBorder` - border of regular windows.
--- * `MiniFilesBorderModified` - border of windows showing modified buffer.
--- * `MiniFilesCursorLine` - cursor line in explorer windows.
--- * `MiniFilesDirectory` - text and icon representing directory.
--- * `MiniFilesFile` - text representing file.
--- * `MiniFilesNormal` - basic foreground/background highlighting.
--- * `MiniFilesTitle` - title of regular windows.
--- * `MiniFilesTitleFocused` - title of focused window.
```
=> mini.files highlight groups
